select max(count) from (select edge1_to, count(*) from edge1 group by edge1_to) as t;
select max(count) from (select edge2_from, edge2_to, count(*) from edge2 group by edge2_from, edge2_to) as t;
select max(count) from (select edge3_from, edge3_to, count(*) from edge3 group by edge3_from, edge3_to) as t;
select max(count) from (select edge4_from, edge4_to, count(*) from edge4 group by edge4_from, edge4_to) as t;
select max(count) from (select edge5_from, count(*) from edge5 group by edge5_from) as t;
create table t_20 as select edge2_to, count(*) from edge1, edge2 where edge1_to=edge2_from group by edge2_to;
select max(count) from t_20;
create table t_21 as select edge2_from, edge3_to, count(*) from edge2, edge3 where edge2_to=edge3_from group by edge2_from, edge3_to;
select max(count) from t_21;
create table t_22 as select edge3_from, edge4_to, count(*) from edge3, edge4 where edge3_to=edge4_from group by edge3_from, edge4_to;
select max(count) from t_22;
create table t_23 as select edge4_from, count(*) from edge4, edge5 where edge4_to=edge5_from group by edge4_from;
select max(count) from t_23;
create table t_24 as select edge3_to, sum(count) as count from t_20, edge3 where edge2_to=edge3_from group by edge3_to;
select max(count) from t_24;
select max(count) from (select edge2_from, edge4_to, sum(count) as count from t_21, edge4 where edge3_to=edge4_from group by edge2_from, edge4_to) as t;
create table t_26 as select edge3_from, sum(count) as count from t_23, edge3 where edge3_to=edge4_from group by edge3_from;
select max(count) from t_26;
Select max(c) from (select edge4_to, sum(count) as c from edge4,t_24 where edge3_to=edge4_from group by edge4_to) as t;
select max(c) from (select edge2_from, sum(count) as c from edge2,t_26 where edge2_to=edge3_from group by edge2_from) as t;
