select max(count) from (select edge1_from, edge1_to, count(*) from edge1 group by edge1_from, edge1_to) as t;
select max(count) from (select edge2_from, edge2_to, count(*) from edge2 group by edge2_from, edge2_to) as t;
select max(count) from (select edge3_from, edge3_to, count(*) from edge3 group by edge3_from, edge3_to) as t;
select max(count) from (select edge4_from, edge4_to, count(*) from edge4 group by edge4_from, edge4_to) as t;
select max(count) from (select edge5_from, edge5_to, count(*) from edge5 group by edge5_from, edge5_to) as t;
create table t_5 as select edge1_from, edge2_to, count(*) from edge1, edge2 where edge1_to=edge2_from group by edge1_from, edge2_to;
select max(count) from t_5;
create table t_6 as select edge5_from, edge1_to, count(*) from edge5, edge1 where edge5_to=edge1_from group by edge5_from, edge1_to;
select max(count) from t_6;
create table t_7 as select edge2_from, edge3_to, count(*) from edge2, edge3 where edge2_to=edge3_from group by edge2_from, edge3_to;
select max(count) from t_7;
create table t_8 as select edge3_from, edge4_to, count(*) from edge3, edge4 where edge3_to=edge4_from group by edge3_from, edge4_to;
select max(count) from t_8;
create table t_9 as select edge4_from, edge5_to, count(*) from edge4, edge5 where edge4_to=edge5_from group by edge4_from, edge5_to;
select max(count) from t_9;
create table t_10 as select edge1_from, edge3_to, sum(count) as count from t_5, edge3 where edge2_to=edge3_from group by edge1_from, edge3_to;
select max(count) from t_10;
create table t_11 as select edge5_from, edge2_to, sum(count) as count from t_5, edge5 where edge5_to=edge1_from group by edge5_from, edge2_to;
select max(count) from t_11;
create table t_12 as select edge4_from, edge1_to, sum(count) as count from t_9, edge1 where edge5_to=edge1_from group by edge4_from, edge1_to;
select max(count) from t_12;
create table t_13 as select edge2_from, edge4_to, sum(count) as count from t_7, edge4 where edge3_to=edge4_from group by edge2_from, edge4_to;
select max(count) from t_13;
create table t_14 as select edge3_from, edge5_to, sum(count) as count from t_9, edge3 where edge3_to=edge4_from group by edge3_from, edge5_to;
select max(count) from t_14;
select max(c) from(select edge1_from, edge4_to, sum(count) as c from t_10, edge4 where edge3_to=edge4_from group by edge1_from, edge4_to) as t;
select max(c) from(select edge5_from, edge3_to, sum(count) as c from t_10, edge5 where edge5_to=edge1_from group by edge5_from, edge3_to) as t;
select max(c) from(select edge4_from, edge2_to, sum(count) as c from t_11, edge4 where edge4_to=edge5_from group by edge4_from, edge2_to) as t;
select max(c) from(select edge3_from, edge1_to, sum(count) as c from t_14, edge1 where edge5_to=edge1_from group by edge3_from, edge1_to) as t;
select max(c) from(select edge2_from, edge5_to, sum(count) as c from t_14, edge2 where edge2_to=edge3_from group by edge2_from, edge5_to) as t;
