CREATE TABLE EDGE1 (EDGE1_FROM INTEGER NOT NULL,EDGE1_TO INTEGER NOT NULL);
CREATE TABLE EDGE2 (EDGE2_FROM INTEGER NOT NULL,EDGE2_TO INTEGER NOT NULL);
CREATE TABLE EDGE3 (EDGE3_FROM INTEGER NOT NULL,EDGE3_TO INTEGER NOT NULL);
CREATE TABLE EDGE4 (EDGE4_FROM INTEGER NOT NULL,EDGE4_TO INTEGER NOT NULL);
CREATE TABLE EDGE5 (EDGE5_FROM INTEGER NOT NULL,EDGE5_TO INTEGER NOT NULL);
